# If you do not have OpenSSL installed, update
# the following line to use 'http://' instead
source 'https://rubygems.org'

gem 'slim', '>= 3.0'

# For faster file watcher updates on Windows:
gem 'wdm', '~> 0.1.0', platforms: [:mswin, :mingw]

# windows does not come with time zone data
gem 'tzinfo-data', platforms: [:mswin, :mingw]

# Middleman Gems
gem 'middleman', '~> 4.4', '>= 4.4.0'
gem 'middleman-autoprefixer', '>= 2.9.0'
gem 'middleman-livereload', '>= 3.4.7'
gem 'middleman-s3_sync', '>= 4.5.0'
gem 'middleman-sprockets', '~> 4.0.0.0.0'
gem 'middleman-blog', '~> 4.0', '>= 4.0.2'
gem 'middleman-syntax', '>= 3.2.0'
gem 'middleman-minify-html'
gem 'mime-types'

gem 'rubocop', require: false
gem 'scss_lint', require: false
gem 'checker', require: false

group :development do
  gem 'pry'
end
